# Generated by Django 4.2.2 on 2023-06-12 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'категория', 'verbose_name_plural': 'категории'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': 'подкатегория', 'verbose_name_plural': 'подкатегории'},
        ),
    ]
